/**
 * TAM KAPSAMLI CHLORELLA MODEL - TYPE DEFINITIONS
 * İstatistik modülü gibi alt sistem olarak tasarlandı
 * Tüm sistemler bu tipleri kullanabilir
 */

// Risk Seviyeleri (5 seviye)
export const RiskLevel = {
  SAFE: 'SAFE',           // 0-20%: Güvenli
  WATCH: 'WATCH',         // 21-40%: İzleme
  ALERT: 'ALERT',         // 41-60%: Dikkat
  CRITICAL: 'CRITICAL',   // 61-80%: Kritik
  COLLAPSE: 'COLLAPSE'    // 81-100%: Çöküş
};

// Nesil Aşamaları (4 aşama)
export const GenerationStage = {
  YOUNG: 'YOUNG',       // Genç hücreler (0-2 gün)
  MATURE: 'MATURE',     // Olgun hücreler (3-5 gün)
  OLD: 'OLD',           // Yaşlı hücreler (6-8 gün)
  DAMAGED: 'DAMAGED'    // Hasarlı hücreler (9+ gün)
};

// Sistem Durumu (her zaman adımında kaydedilir)
export const createSystemState = () => ({
  timestamp: new Date(),
  X: 0,              // Biyokütle (g/L)
  pH: 7.5,
  temperature: 25,   // °C
  O2: 8.0,           // mg/L (Dissolved Oxygen)
  CO2: 5.0,          // mg/L
  TAN: 10.0,         // mg/L (Total Ammonia Nitrogen)
  NO3: 20.0,         // mg/L (Nitrat)
  EC: 1500,          // μS/cm (Elektriksel İletkenlik)
  alkalinity: 100,   // mg/L CaCO3
  OD750: 0.1,        // Optik Yoğunluk (750 nm)
  cellDensity: 1e6,  // cells/mL
  NH3: null,         // mg/L (serbest amonyak - hesaplanacak)
  NH4: null          // mg/L (amonyum iyonu - hesaplanacak)
});

// Risk Değerlendirmesi (16 risk senaryosu)
export const createRiskAssessment = () => ({
  NH3_toxicity: 0,          // Amonyak toksisitesi
  night_hypoxia: 0,         // Gece hipoksisi
  photooxidation: 0,        // Fotoöksidasyon
  N_limitation: 0,          // Azot sınırlaması
  pH_fluctuation: 0,        // pH dalgalanması
  carbon_limitation: 0,     // Karbon sınırlaması
  osmotic_stress: 0,        // Osmotik stres
  heat_stress: 0,           // Sıcaklık stresi
  contamination: 0,         // Kontaminasyon
  light_heterogeneity: 0,   // Işık heterojenliği
  sedimentation: 0,         // Sedimentasyon
  heavy_metal: 0,           // Ağır metal toksisitesi
  vitamin_deficiency: 0,    // Vitamin eksikliği
  temperature_shock: 0,     // Sıcaklık şoku
  mechanical_damage: 0,     // Mekanik hasar
  biofilm: 0                // Biyofilm oluşumu
});

// Su Kimyası Parametreleri
export const createWaterChemistry = () => ({
  volume: 100,         // L
  pH: 7.5,
  alkalinity: 100,     // mg/L CaCO3
  hardness: 150,       // mg/L CaCO3
  temperature: 25,     // °C
  EC: 1500,           // μS/cm
  TDS: 750,           // mg/L (Total Dissolved Solids)
  Ca: 40,             // mg/L
  Mg: 10,             // mg/L
  Na: 20,             // mg/L
  K: 5                // mg/L
});

// Model Parametreleri
export const createModelParams = () => ({
  // Büyüme sabitleri
  mu_max: 1.2,         // 1/day (maksimum spesifik büyüme hızı)
  K_N: 5.0,            // mg/L (azot için Monod sabiti)
  K_P: 0.5,            // mg/L (fosfor için Monod sabiti)
  K_CO2: 2.0,          // mg/L (CO2 için Monod sabiti)
  K_I: 50,             // μmol/m²/s (ışık doygunluk sabiti)
  
  // Stokiyometri
  Y_N: 0.08,           // g biomass / g N
  Y_P: 0.45,           // g biomass / g P
  Y_CO2: 1.88,         // g biomass / g CO2
  
  // Ölüm ve solunum
  k_d: 0.05,           // 1/day (ölüm hızı)
  k_resp: 0.1,         // 1/day (solunum hızı)
  
  // pH ve sıcaklık
  pH_opt: 7.5,
  pH_min: 6.5,
  pH_max: 9.0,
  T_opt: 28,           // °C
  T_min: 15,
  T_max: 35,
  
  // Işık
  I_max: 200,          // μmol/m²/s
  I_opt: 150,
  photoperiod: 16      // saat/gün
});

// Müdahale Tipi
export const InterventionType = {
  NUTRIENT_ADDITION: 'NUTRIENT_ADDITION',
  PH_ADJUSTMENT: 'PH_ADJUSTMENT',
  TEMPERATURE_CHANGE: 'TEMPERATURE_CHANGE',
  DILUTION: 'DILUTION',
  HARVEST: 'HARVEST',
  CO2_INJECTION: 'CO2_INJECTION',
  AERATION: 'AERATION',
  LIGHT_CHANGE: 'LIGHT_CHANGE'
};

// Müdahale kaydı
export const createIntervention = (type, params) => ({
  timestamp: new Date(),
  type,
  params,
  autoGenerated: false,
  approved: false
});

export default {
  RiskLevel,
  GenerationStage,
  InterventionType,
  createSystemState,
  createRiskAssessment,
  createWaterChemistry,
  createModelParams,
  createIntervention
};
